### ISSUE TITLE
block/Item "conflict" with mekanism

### ISSUE THREAD

**Issue by cbcercas** [Toops/TinkersSteelworks#1]
There is a problem with block of coal with mekanism mod.
When adding mekanism TinkersSteelworks block of has no recipe and can't be converted from mekanism with an ore converter 

I use : 
Tinckers 1.6.4_1.5.3
TinkersSteelworks 0.0.2 & 0.0.3d1
forge 1.6.4-Forge9.11.1.965

**Comment by Toops** [comment]
I see the problem, I think. I'm registering it as blockCoal while Mekenism is registering it as blockCharcoal. Makes more sense, I suppose. This will be fixed for the next release. I truly appreciate the report!

**Comment by Toops** [comment]
Fixed a while back in the dev versions, and now the fix is rolled into the newest stable release.
Thanks again!
