### ISSUE TITLE
unable to build from ant

### ISSUE THREAD

**Issue by wisthy** [Toops/TinkersSteelworks#19]
When I try to build the project using ant, I have the following error:

BUILD FAILED
C:\Users\wisthler\git\TinkersSteelworks\build.xml:179: C:\Users\wisthler\git\TinkersSteelworks\build\forge\mcp\reobf\minecraft\tsteelworks does not exist.

Below, the complete log trace of the ant execution:

https://gist.github.com/wisthy/11405242

**Comment by Toops** [comment]
Hmmm, how odd. Works fine for me. I'll have to dig around a bit more...

**Comment by wisthy** [comment]
maybe something you have installed/copied manually?

**Comment by wisthy** [comment]
https://gist.github.com/wisthy/11405242

I tried again after a "clean" and the error is a little bit different. Apparentrly, the issue is during the configuration of Forge.

**Comment by Toops** [comment]
Confirmed. I just tried it straight out of a folder from the github source, and got the same ordeal. My normal build folder has been toyed around - I'd actually originally copied my working source folder (the one I use to edit from with eclipse) to the desktop, and when it's time to build, I just overwrite any necessary files. Wise? Not at all, but it's what has been working for me. I'll see if I can get this sorted out, though. EDIT: Come to think of it, in earlier versions I tried this and didn't have this problem. Hmmmm. Time to look through old commits...

In that fresh copy I mentioned, when I manually replace the files it's looking for into the directory with those from my normal build directory, it _builds_ but none of the sources actually go into the jar - only resources and such. I'm still pretty new to all this, and that's especially true when it comes to compiling against forge and using build scripts, so please forgive my noobisms.

**Comment by Toops** [comment]
Here's a copy of my build directory. https://dl.dropboxusercontent.com/u/11017392/Minecraft/TSteelworks%20Workspace.zip

That's what I use to build out of, not actually work out of. That said, its sources and such aren't current, but that doesn't matter.

**Comment by wisthy** [comment]
with the build/\* from your zip, I can now generate the jar. It's enough for me for the moment
