### ISSUE TITLE
Crash with the High oven

### ISSUE THREAD

**Issue by terrapinlogo** [Toops/TinkersSteelworks#20]
Occurred when placing/removing charcoal from the high oven controller top (oxidiser?) slot. Using Agrarian Skies 2.1.2 mod pack playing on the platform map

Crash log http://pastebin.com/ZN97pFJ9

**Comment by Toops** [comment]
This should also be fixed as of 0.0.4.1 of TSteelworks. We'll just have to wait for Agrarian Skies to update as well~

Thanks for the report,
