### ISSUE TITLE
issue with Deep Tank size

### ISSUE THREAD

**Issue by wisthy** [Toops/TinkersSteelworks#21]
On the new 0.0.4.1 version, if I build a 3x3x3 Deep Tank, it doesn't work, I receive an "invalid structure".

If I upgrade it to a 3x3 basement with 4 high, it works just fine.

(you can assign the issue to me, I'll check that. Hopefully later today or at latest tomorrow)

**Comment by wisthy** [comment]
Maybe found the issue. DeepTankLogic lines 289 and 291. It should probably be greater than 0 instead of 1.

**Comment by Toops** [comment]
Horray for killing two birds with one stone!
(Just found out how to assign things!)

That section does look like the likely cause.

**Comment by wisthy** [comment]
tested succesfully with the dev version
