### ISSUE TITLE
issue with High Oven structure

### ISSUE THREAD

**Issue by wisthy** [Toops/TinkersSteelworks#22]
I've built a High Oven with base 3x3 then I added 2 hollow layer then a plain 3x3 top. The high oven works with 2 meltables slot.

XXX  XXX  XXX XXX
XXX  XoX  XoX XXX
XXX  XcX  XXX XXX

X: scorched brick
c: controller
o: empty air block

from left to right = from bottom to top

Then, I decided to increase the size of the High Oven. I broke the central block of the top layer (so 3x3 plain base + 3 hollow layers) and the High Oven works with 3 internal slots.

XXX  XXX  XXX XXX
XXX  XoX  XoX XoX
XXX  XcX  XXX XXX

Does it not need a plain top layer for that?

same remark as the other issue, you can assign it to me

Update:

when I log off / log on again. The High Oven is back to 2 internal slots but works fine that way. If I put a scorched brick in the hollow of the 4th layer (3rd if we don't count the bottow one) and break it directly after, the high oven has 3 internal slots again.

**Comment by wisthy** [comment]
Problem probably comes from method checkValidStructure. I'll fix it tommorrow.

**Comment by Toops** [comment]
Yeah, its structure scanning and validation checks has been needing some attention for a while now. There were some recent changes to the smeltery for similar reasons (validation), so that may be a good reference. Oddly, I'd never tried actually using the thing while a block is removed from the top. I'm a bad betatester.

**Comment by wisthy** [comment]
Tested my fix but still the same issue. I'll have to investigate further

http://imgur.com/bHMnelj

**Comment by wisthy** [comment]
tested again and now it works fine. Probably an issue with the jar generation as it was my first generation
