### ISSUE TITLE
tank validation is ignored

### ISSUE THREAD

**Issue by wisthy** [Toops/TinkersSteelworks#26]
when the deep tank is invalid we can still pump fluid out of it or into it.

tested on latest dev version (the one that fix toops#21 and toops#22)

**Comment by Toops** [comment]
The temporary solution in 0.0.4.2 fixes this currently, though in the long run I would like to go with your IMaster interface, or at least something similar, for cleanliness.

So we'll call this one resolved for the moment.

**Comment by wisthy** [comment]
I've prepared a temporary hybrid solution. I'll test it when I go home this evening.
