### ISSUE TITLE
Crash with seared duct output

### ISSUE THREAD

**Issue by HaraldKorneliussen** [Toops/TinkersSteelworks#33]
I just ran into a crash which freezes my Agrarian Skies 2.1.2 world on startup, as I was a little too reckless with those seared ducts.

I was making seared brick with the usual recipe, and the bricks got output to the duct just fine. Then I had the idea of trying to use the same duct to input stone for the reaction. That crashed it. I don't recall if it crashed when I put in the stack of stone, or when I changed the mode of the oven. From the crash log:

Description: Ticking tile entity

java.lang.NullPointerException at tsteelworks.blocks.logic.HighOvenDuctLogic.func_94041_b(HighOvenDuctLogic.java:558)
        at tsteelworks.blocks.logic.HighOvenLogic.sendItemToDuct(HighOvenLogic.java:1062)
        at tsteelworks.blocks.logic.HighOvenLogic.addSolidItem(HighOvenLogic.java:1036)

**Comment by wisthy** [comment]
We changed a lot of things about the duct in the new release so I suggest you to update to agrarian skies 2.1.3 which includes the last version of this mod. Maybe we already fixed your issue in it.

update: it doesn't mean we will not look into it. We will test it ourself in the newer version to find out if we already fixed the issue or not. But this way, you can try yourself in the meantime.

**Comment by wisthy** [comment]
I confirm that modification done in newest version should fix this particular error. But it still need to be tested to be sure there is nothing hidding behind that need a new fix.

**Comment by Toops** [comment]
Totally fixed as of release 0.0.4.2-fix2: https://github.com/Toops/TinkersSteelworks/releases/tag/v0.0.4.2-fix2
Thanks for the report @vintermann 
And as always, good lookin' out, @wisthy :+1:
