### ISSUE TITLE
Deep Tank storaged fluids seeming to exceed it's volume

### ISSUE THREAD

**Issue by dredgemage** [Toops/TinkersSteelworks#42]
I was in the process of trying to automate the production of steam in a High Oven and was using a Deep Tank as storage, when I noticed what appears to be a rendering glitch (but might actually be due to the amount of fluid stored being in the tank, I don't know their limits). My setup and the bug itself can be seen in the link below.
http://screenshotuploader.com/s/1405co4c9

The tank itself has a 3x3 base and is 5 blocks tall and when I look at the controller with WAILA it reports it holding 40,497mB of steam and 31,999mB of water. An image of the GUI for the controller is linked below.
http://screenshotuploader.com/s/1405ed_fp

Versions
Agrarian Skies modpack: 2.1.5
-Tinkers' Construct: 1.5.5.7
-Tinkers' Steelworks: 0.0.4.2

**Comment by wisthy** [comment]
It's the first time I see it on an Deep Tank but I saw this particular issue many times on smelteries. And as we re-used the logic from the smelteries, it's logical that we have the same issue on our side.

If I have to bet, I'll say that the issue only occurs when there are several fluid in the system (in your case, water and steam)

**Comment by wisthy** [comment]
I checked the code. The capacity of a Deep Tank is 4 buckets for each "inner block" but I'm not really sure of the definition of inner block... Apparently, the top layer and bottom layer are not included on the inner blocks. I'll have to confirm that and check for the walls.

If the walls are not considered as inner blocks, your Deep Tank 3x3x5 has an capacity of 108 buckets and so we have a rendering issue and not a capacity issue.

If the walls are not inner blocks, the capacity goes down to 12 buckets (which seems really low to me) and then we have a capacity issue.

**Comment by dredgemage** [comment]
I repeated the system with the exact same layout once to export only steam to the Deep Tank through the High Oven and one to export only water to the Deep Tank through the High Oven. Both times the tank maxed out at 31,999mB without the bug happening. (but more of the fluid would go into the drain without showing up in the tank which is a whole different bug I figure)
That would mean that your bet is spot on but the calculations for the size of the tank are off seeing as a bucket is 1,000mB.

**Comment by wisthy** [comment]
So, it has an internal capacity of 32 buckets, which means 8 internal blocks which has no sense...

Or the multiplicator 4 buckets per block has been changed in the configuration for Agrarian Skies.

**Comment by wisthy** [comment]
when we are at it, we also have to fix the same issue as SlimeKnights/TinkersConstruct#558

**Comment by dredgemage** [comment]
Spot on guess there, checked the config and found this: I:"Fluid Capacity Multiplier"=8. That does mean the capacity is correct.

**Comment by wisthy** [comment]
ok, so, it's not a capacity issue but a rendering issue. So, @Toops, it's for you :p
