### ISSUE TITLE
Limestone still crashes

### ISSUE THREAD

**Issue by joshiejack** [Toops/TinkersSteelworks#49]
Toops you also need to check if the chunk exists before checking whether a block is water material or not. Otherwise you're calling on a block that doesn't exist because the chunk doesn't exist. Since it's still causing crashes in some cases.

https://github.com/Toops/TinkersSteelworks/blob/master/src/tsteelworks/worldgen/WorldGenLimestone.java#L29

Since it will be trying to get a material for a block that doesn't exist

**Comment by wisthy** [comment]
added the test as suggested but I prefer to have @Toops looking at it first. I'm not familiar enough with the Forge API yet.

**Comment by Toops** [comment]
Tested and totally confirmed as fixed as of https://github.com/Toops/TinkersSteelworks/commit/ff9a62dfe21d175ccc0cc66908d3b3f39e8bf5a7
Thanks @joshiejack and @wisthy :+1:
