### ISSUE TITLE
Italics/Colors in tooltips and such.

### ISSUE THREAD

**Issue by Enosphorous** [Toops/TinkersSteelworks#53]
Toops, I noticed that for your original WAILA integration, you're using the difficult and overcomplicated method of italicizing text. I'm not sure if this helps anything, but a much easier way to do italics on text is to use EnumChatFormatting. So, for example, when you add to the currenttip, you would use something like:

currenttip.add(EnumChatFormatting.ITALICS + (StatCollector.translateToLocal("tconstruct.waila.empty")));

Don't know if you had already seen that, or if you had decided against using it, just wanted to point it out in case it would be helpful.

**Comment by Toops** [comment]
Oh, thanks! I completely forgot about that. The other way suddenly started causing compile errors anyway, so I begrudgingly yanked it. I'll make sure to do the same for TCon. :)

**Comment by Enosphorous** [comment]
Okay, great, glad I could help! 

Also, I'll get to adding the Scorched Faucet at some point. I'm a bit busy with finals at the moment, but I can most likely get it done in the next couple of days.
