### ISSUE TITLE
Deep tank crashes and corrupts world when adding a duct

### ISSUE THREAD

**Issue by Ylvakiller** [Toops/TinkersSteelworks#68]
Hi there, I am running an agrarian skies server, no additions or changes to the modpack whatsover, we are running version 2.1.8.

one of the players made a deeptank and added a duct to allow molten metals to get into that deep tank. this crashed the server and now it is refusing to start up again.

crash report can be found here : http://pastebin.com/JJdq6nnS

**Comment by Ylvakiller** [comment]
Just a note, I used mc edit to remove the duct block, reloaded that world, and it crashed on the same error, I then removed the complete deep tank structure, and the world loaded correctly again.

I still think you should be aware of this error, so I'll keep this issue open for now

**Comment by Toops** [comment]
Ah yes, this was fixed as of 0.0.4.2-fix2: https://github.com/Toops/TinkersSteelworks/releases/tag/v0.0.4.2-fix2
Also, ducts are for items, drains are for fluids. ;)
Report much appreciated, though.
